name: fmnist
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - python=3.9.13
  - pip=21.2.4
  - pytorch=1.12.0
  - pytorch-lightning=1.6.4
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - pip:
    - hydra-core==1.2.0
