trainer:
  nepochs: 20
  accelerator: gpu
  gpus: 1
model:
  start_lr: 0.0001
data:
  train_dataloader:
    batch_size: 64
    num_workers: 2
    shuffle: True
  val_dataloader:
    batch_size: 64
    num_workers: 2
    shuffle: False
